---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  vars:
    kernel:
      default: arch-lts
      rootuuid: 78da4ebd-5eba-4a7c-8caf-5f297eece0a7

  tasks:
    - {import_role: name=system tasks_from=kernel, tags: ['kernel']}
    - {import_role: name=system tasks_from=base, tags: ['base']}
    - {import_role: name=system tasks_from=nvidia, tags: ['nvidia']}
    - {import_role: name=system tasks_from=gnome, tags: ['gnome']}
    - {import_role: name=system tasks_from=userapps, tags: ['userapps']}
