- name: base > User viny
  ansible.builtin.user:
    name: viny
    group: viny
    shell: /bin/zsh
    groups: uucp,wheel
    append: yes

- name: base > Install my base apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - chromium
      - firefox
      - thunderbird,thunderbird-i18n-fr 
      - gnucash
      - hunspell,hunspell-fr
      - inkscape
      - ttf-dejavu
      - keepassxc
      - mpc,ncmpcpp
      - pdfarranger
      - quodlibet
      - syncthing
      - vlc

- name: base > Install PortfolioPerformance dependencies
  community.general.pacman: name=jre-openjdk
