- name: nvidia > Install Nvidia driver
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - nvidia-dkms
      - nvidia-utils
      - nvidia-settings
      - nvtop
      - opencl-nvidia

- name: nvidia > Install Video Decode and Presentation API for UNIX (VDPAU) packages
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - libvdpau
      - libva-vdpau-driver 
      - vdpauinfo
