- name: userapps > User viny
  ansible.builtin.user: name=viny group=viny shell=/bin/zsh groups=uucp,wheel append=yes

- name: userapps > Install my base apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - chromium
      - firefox
      - thunderbird,thunderbird-i18n-fr 
      - gnucash
      - hunspell,hunspell-fr
      - inkscape
      - keepassxc
      - ncmpcpp
      - pdfarranger
      - quodlibet
      - vlc

- name: userapps > Install THE text editor, but I don't known which one it is yet :)
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - helix
      - neovim
      - xsel

- name: userapps > Install photo management softwares
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - exiv2
      - imagemagick
      - perl-image-exiftool
      - shotwell

- name: userapps > Install dev tools
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - cmake
      - dotnet-runtime,dotnet-sdk
      - gdb
      - gnome-builder
      - heaptrack
      - jre-openjdk
      - lcov
      - minicom
      - perf
      - python-pre-commit

- name: userapps > KiCad
  community.general.pacman: name=kicad,kicad-library

- name: userapps > Install Saleae Logic 2 dependencies
  community.general.pacman: name=libxcrypt-compat

- name: userapps > Install custom udev rules
  ansible.builtin.copy: src=udev/{{ item }} dest=/etc/udev/rules.d/{{ item }} mode=0644
  with_items:
    - esp32.rules
    - raspberry.rules
    - saleae.rules
    - steam-controllers.rules
