- name: userapps > User viny
  ansible.builtin.user: name=viny group=viny shell=/bin/zsh groups=uucp,wheel append=yes

- name: userapps > Install base apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - chromium
      - firefox
      - thunderbird,thunderbird-i18n-fr 
      - gnucash
      - hunspell,hunspell-fr
      - inkscape
      - keepassxc
      - ncmpcpp
      - pdfarranger
      - quodlibet
      - vlc

- name: userapps > Install base apps (flatpacks)
  community.general.flatpak: name={{ flatpaks | join(',') }}
  vars:
    flatpaks:
      - io.kopia.KopiaUI
      - org.freac.freac

- name: userapps > Install THE text editor, but I don't known which one it is yet :)
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - helix
      - neovim
      - xsel

- name: userapps > Install photo management softwares
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - darktable
      - exiv2
      - imagemagick
      - perl-image-exiftool
      - shotwell

- name: userapps > Install Steam
  community.general.flatpak: name={{ flatpaks | join(',') }}
  vars:
    flatpaks:
      - com.valvesoftware.Steam
      - com.valvesoftware.Steam.CompatibilityTool.Proton

- name: userapps > Install KiCad
  community.general.pacman: name=kicad,kicad-library

- name: userapps > Install C/C++ dev tools
  community.general.pacman: name=heaptrack,lcov,perf

- name: userapps > Install JRE OpenJDK
  community.general.pacman: name=jre-openjdk

- name: userapps > Install .NET and PowerShell
  community.general.pacman: name=dotnet-runtime,dotnet-sdk  

- name: userapps > Install Saleae Logic 2 dependencies
  community.general.pacman: name=libxcrypt-compat
